export const LOGICAL_WIDTH = 390;
export const LOGICAL_HEIGHT = 844;
export const SURFACE_Y = 150;
export const BOTTOM_Y = 820;
export const BOTTOM_SAFE_AREA = 40;
export const MAX_DEPTH_LIMIT = 4000; // cho phép lặn sâu hơn nhiều
export const INITIAL_MAX_DEPTH = 550;
export const DEPTH_UPGRADE_DELTA = 200;
export const SPAWN_PREVIEW_BUFFER = 90;
export const INITIAL_NET_SIZE = 22;
export const INITIAL_PULL_SPEED = 220;
export const INITIAL_CAPACITY = 3;
export const NET_SIZE_UPGRADE_DELTA = 3;
export const PULL_SPEED_UPGRADE_DELTA = 20;
export const CAPACITY_UPGRADE_DELTA = 1;
export const ROUND_FEEDBACK_DURATION_MS = 1100;
